language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master

# install, test & build
install:
  - yarn
  - yarn test
  - yarn build

# deploy: storybook to firebase, library to npm.js
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
      on:
        tags: true
        branch: master
