language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

# install & test
install:
  - yarn

after_success:
  - yarn test:coveralls

# deploy
deploy:
  - provider: script
    script: bash scripts/deploy_storybook.sh $FIREBASE_PROJECT_ID $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy_library.sh
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
