language: node_js
node_js:
  - "10.7"

notifications:
  email: false

branches:
  only:
    - master
    - echo "Master branch"

script:
  - echo "Deploying!"
install:
  - yarn
  - yarn test
after_success:
  - echo "Deploy"

# build storybook
# deploy storybook to firebase/ghPages
# deploy package to npm
