language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

# install & test
install:
  - yarn

# deploy
jobs:
  include:
    # run tests
    - stage: test
      script:
        - yarn test
    # run tests for coverage
    - stage: test coverage
      if: (branch = master) AND (NOT (type IN (pull_request)))
      script:
        - yarn test:coveralls
    # deploy storybook to firebase
    - stage: deploy to firebase
      if: (branch = master) AND (NOT (type IN (pull_request)))
      script:
        - yarn build:storybook
      deploy:
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: $FIREBASE_PROJECT_ID
        skip_cleanup: true
        on:
          branch: master
    # deploy library to npm
    - stage: deploy to npm
      if: tag IS present
      script:
        - yarn build:library
        - cp package.json lib/
        - cd lib/
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
