language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master

# install, test & build
install:
  - yarn
  - yarn test
  - yarn build

# deploy:
# - storybook to firebase when merging pr
# - library to npm.js when merging pr
deploy:
- provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT_ID
  on:
    branch: master
- provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master
