language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master

# install, test & build
install:
  - yarn
  - yarn test
  - yarn build

# deploy: storybook to firebase, library to npm.js
deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $FIREBASE_PROJECT_ID
    skip_cleanup: true
    on:
      branch: master
