language: node_js
node_js:
  - "10.7"

notifications:
  email: false

# push to branches only trigger on master (merge pr)
branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

# install & test
install:
  - yarn
  - yarn test:coveralls

# build for deployment
before_deploy:
  - yarn build:storybook
  - yarn build:library
  - cp package.json lib/

# deploy: storybook to firebase, library to npm.js
deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $FIREBASE_PROJECT_ID
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    upload-dir: lib/
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
